// Generated by https://quicktype.io

import { Role } from "./role.interface";

export interface CheckTokenResponse {
    id:             string;
    email:          string;
    firstName:      string;
    lastName:       string;
    roles:           Role[];
    status:         string;
    clientId:       string | null;
    clientStatus:   string;
    createdAt:      string;
    updatedAt:      string;
}
